name: Go

on:
  - push
  - pull_request

jobs:
  fmt_vet:
    name: Fmt & Vet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: go fmt
        run: |
          output=$(gofmt -s -d .)
          echo "$output"
          test -z "$output"
      - name: go vet
        run: go vet ./...

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: go test
        run: go test -covermode atomic -coverprofile=covprofile ./...
      - name: install goveralls
        run: go install github.com/mattn/goveralls@latest
      - name: send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=covprofile -service=github
